version: '3.6'

services:
  fake-gcs-server:
    container_name: fake-gcs-server
    image: fsouza/fake-gcs-server
    command: "-scheme http"
    restart: always
    ports:
      - 4443:4443
    volumes:
       - gcs_storge:/storage
    networks:
      - pixel-artist-dev-net
  # sftp-mock:
    container_name: sftp-mock
    image: atmoz/sftp
    restart: always
    environment:
      SFTP_USERS: ${SFTP_USERS} # don't set root which is a default user.
    ports:
      - 2222:22
    volumes:
       - sftp_mock_data:${SFTP_PATH}
    networks:
      - pixel-artist-dev-net

  # postgres:
    container_name: postgres
    image: postgres:alpine3.20
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
       - db_volume:/data/postgres
    networks:
      - pixel-artist-dev-net

  pixel-artist-backend:
    container_name: pixel-artist-backend
    build: .
    environment:
      - STORAGE_EMULATOR_HOST=http://fake-gcs-server:4443
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - 10000:10000
    volumes:
       - $PWD:/app
    networks:
      - pixel-artist-dev-net

networks:
  pixel-artist-dev-net:
    external: true

volumes:
  db_volume:
  sftp_mock_data:
    external: true
  gcs_storge:
    external: true