version: '3.6'
services:
  fake-gcs-server:
    container_name: fake-gcs-server
    image: fsouza/fake-gcs-server
    command: "-scheme http"
    restart: always
    ports:
      - 4443:4443
    volumes:
       - gcs_storge:/storage
    networks:
      - pixel-artist-dev-net
networks:
  pixel-artist-dev-net:
    external: true
volumes:
  gcs_storge:
    external: true